import forge from 'node-forge';

const caCertificates = [
    // For ateamer.de
    "-----BEGIN CERTIFICATE-----\n" +
    "MIIERTCCA66gAwIBAgIQM2VQCHmtc+IwueAdDX+skTANBgkqhkiG9w0BAQUFADCB\n" +
    "zjELMAkGA1UEBhMCWkExFTATBgNVBAgTDFdlc3Rlcm4gQ2FwZTESMBAGA1UEBxMJ\n" +
    "Q2FwZSBUb3duMR0wGwYDVQQKExRUaGF3dGUgQ29uc3VsdGluZyBjYzEoMCYGA1UE\n" +
    "CxMfQ2VydGlmaWNhdGlvbiBTZXJ2aWNlcyBEaXZpc2lvbjEhMB8GA1UEAxMYVGhh\n" +
    "d3RlIFByZW1pdW0gU2VydmVyIENBMSgwJgYJKoZIhvcNAQkBFhlwcmVtaXVtLXNl\n" +
    "cnZlckB0aGF3dGUuY29tMB4XDTA2MTExNzAwMDAwMFoXDTIwMTIzMDIzNTk1OVow\n" +
    "gakxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwx0aGF3dGUsIEluYy4xKDAmBgNVBAsT\n" +
    "H0NlcnRpZmljYXRpb24gU2VydmljZXMgRGl2aXNpb24xODA2BgNVBAsTLyhjKSAy\n" +
    "MDA2IHRoYXd0ZSwgSW5jLiAtIEZvciBhdXRob3JpemVkIHVzZSBvbmx5MR8wHQYD\n" +
    "VQQDExZ0aGF3dGUgUHJpbWFyeSBSb290IENBMIIBIjANBgkqhkiG9w0BAQEFAAOC\n" +
    "AQ8AMIIBCgKCAQEArKDw+4BZ1JzHpM+doVlzCRBFDA0sbmjxbFtIaElZN/wLMxnC\n" +
    "d3/MEC2VNBzm600JpxzSuMmXNgK3idQkXwbAzESUlI0CYm/rWt0RjSiaXISQEHoN\n" +
    "vXRmL2o4oOLVVETrHQefB7pv7un9Tgsp9T6EoAHxnKv4HH6JpOih2HFlDaNRe+68\n" +
    "0iJgDblbnd+6/FFbC6+Ysuku6QToYofeK8jXTsFMZB7dz4dYukpPymgHHRydSsbV\n" +
    "L5HMfHFyHMXAZ+sy/cmSXJTahcCbv1N9Kwn0jJ2RH5dqUsveCTakd9h7h1BE1T5u\n" +
    "KWn7OUkmHgmlgHtALevoJ4XJ/mH9fuZ8lx3VnQIDAQABo4HCMIG/MA8GA1UdEwEB\n" +
    "/wQFMAMBAf8wOwYDVR0gBDQwMjAwBgRVHSAAMCgwJgYIKwYBBQUHAgEWGmh0dHBz\n" +
    "Oi8vd3d3LnRoYXd0ZS5jb20vY3BzMA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQU\n" +
    "e1tFz6/Oy3r9MZIaarbzRutXSFAwQAYDVR0fBDkwNzA1oDOgMYYvaHR0cDovL2Ny\n" +
    "bC50aGF3dGUuY29tL1RoYXd0ZVByZW1pdW1TZXJ2ZXJDQS5jcmwwDQYJKoZIhvcN\n" +
    "AQEFBQADgYEAhKhMyT4qvJrizI8LsiV3xGGJiWNa1KMVQNT7Xj+0Q+pjFytrmXSe\n" +
    "Cajd1FYVLnp5MV9jllMbNNkV6k9tcMq+9oKp7dqFd8x2HGqBCiHYQZl/Xi6Cweiq\n" +
    "95OBBaqStB+3msAHF/XLxrRMDtdW3HEgdDjWdMbWj2uvi42gbCkLYeA=\n" +
    "-----END CERTIFICATE-----",
    // LOB Test CA
    "-----BEGIN CERTIFICATE-----\n" +
    "MIIDhjCCAm6gAwIBAgIBATANBgkqhkiG9w0BAQsFADB0MRQwEgYDVQQDDAtMT0Ig\n" +
    "VGVzdCBDQTEMMAoGA1UECgwDTE9CMQwwCgYDVQQIDANOUlcxCzAJBgNVBAYTAkRF\n" +
    "MRAwDgYDVQQHDAdDb2xvZ25lMSEwHwYJKoZIhvcNAQkBFhJhbGV4QGFsZXhob3Bw\n" +
    "ZW4uZGUwHhcNMTgwMTA2MTUzNzAyWhcNMTgxMjMxMTUzNzAyWjB0MRQwEgYDVQQD\n" +
    "DAtMT0IgVGVzdCBDQTEMMAoGA1UECgwDTE9CMQwwCgYDVQQIDANOUlcxCzAJBgNV\n" +
    "BAYTAkRFMRAwDgYDVQQHDAdDb2xvZ25lMSEwHwYJKoZIhvcNAQkBFhJhbGV4QGFs\n" +
    "ZXhob3BwZW4uZGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDSh0pS\n" +
    "5mkqUV2WQ9bEXkwoVLFg5bqDKN5jOuFFT42HhtB+EzmUWb+mGivQrlIF97iqGDO3\n" +
    "ueQD/Tj+qfgPF17aS/I7tJAe0U0qtkjJEl258nKtWRsdTztJC6bt4VYTg/K4aZLD\n" +
    "LGiRHMzGGreaPUH7VmQnoQ3O2IH90gLz8J+QLTpeeaPjnakh4/RABfB2DT1r9ceh\n" +
    "eg4KXliXft21/LBosbB4TrwaefmJOrIcO3JGYpHyFawFrfvdLN/5vJsJe2OyjluX\n" +
    "KG9oI24Dx1ukx3am0fH6bGgjlCMhfFQiENGu6IlanLCaTAzDvd1Elui6llkIk2UT\n" +
    "iI4D80hrRCOCDHenAgMBAAGjIzAhMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/\n" +
    "BAQDAgKEMA0GCSqGSIb3DQEBCwUAA4IBAQCzHxRMMABeTOXaseYPPAn+O6e4n2GS\n" +
    "P4mb0aisyGHDbPncSEHm7xTd5A2VHOnkWd5rqsyYV89aMAM0HrYE2DS/VG503SFE\n" +
    "inearsVCDA/l/eb2tyXWseEPxAGTPxio6vYwQgED51eOr6KEna+NfZhPksAN1ng+\n" +
    "2QUSXAcGcpRyPbNokjiS7eesXl/nzuBSfyMA16TwJgSmMw83a95ehrUW8VVJWyZi\n" +
    "d6e2Cm0435w7xwuvTZt1oZLXw9ZXxaiYPGrksiLkHrcXqFsoUpesNe2vqRL5nvBj\n" +
    "E4l03ZKeZBgUxxhZj5QQGPIUMJ7Mg2Au4dGZDzSxpPE0nibp0MkMR5zE\n" +
    "-----END CERTIFICATE-----\n"
];

export const caStore = forge.pki.createCaStore(caCertificates);